name: 'testify'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    deploy:
      replicas: 6 
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    networks:
      - app_network
    command: [ "npm", "run", "start" ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/public/uploads:/usr/src/db/public/uploads
      - ./backend/logs:/usr/src/db/logs
    deploy:
      replicas: 6 
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    networks:
      - app_network

    entrypoint: [ "/bin/sh", "-c", "npx prisma migrate deploy && npm run start" ]

  reverse-proxy:
    container_name: 'nginx'
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # Expose frontend on port 80
      - "3030:3030"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
