name: 'testify'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    deploy:
      replicas: 6 # Creates 6 frontend containers automatically
    networks:
      - app_network
    command: ["npm", "run", "start"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    deploy:
      replicas: 6 # Creates 6 backend containers automatically
    networks:
      - app_network
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run start"]

  reverse-proxy:
    container_name: 'nginx'
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # Expose frontend on port 80
      - "3030:3030"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
