name: 'testify'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    deploy:
      replicas: 6  # Creates 6 frontend containers automatically
    networks:
      - app_network

  reverse-proxy:
    container_name: 'nginx-backend'
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3030:81"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
